pipeline {
  agent any

  tools {
    nodejs 'node-22.11.0'
  }

  environment {
    REMOTE_SERVER = "172.31.27.164"
    CONTAINER_NAME = 'wm--docs-flow'
    AWS_REGION = 'us-east-1'
    ECR_REPO = 'poc-misc'
    IMAGE_TAG = "dev.wm-docs-flow.${env.BUILD_NUMBER}"
    HTTP_PORT = '8035'
    DEPLOYMENT_KEY = 'wm-docs-ssh-key'
  }

  stages {

    stage('Cleanup') {
      steps {
        sh 'rm -rf .docusaurus build'
      }
    }

    stage('Build App') {
      steps {
        sh '''
          npm ci
          npm run build
        '''
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          withAWS(region: AWS_REGION, credentials: 'wm-ps-user-ecr') {
            def awsAccountID = sh(
              returnStdout: true,
              script: "aws sts get-caller-identity --query Account --output text"
            ).trim()

            sh """
              aws ecr get-login-password --region ${AWS_REGION} \
              | docker login --username AWS --password-stdin \
              ${awsAccountID}.dkr.ecr.${AWS_REGION}.amazonaws.com

              docker buildx build -t ${ECR_REPO}:${IMAGE_TAG} .
            """
          }
        }
      }
    }

    stage('Push to ECR') {
      steps {
        script {
          withAWS(region: AWS_REGION, credentials: 'wm-ps-user-ecr') {
            def awsAccountID = sh(
              returnStdout: true,
              script: "aws sts get-caller-identity --query Account --output text"
            ).trim()

            sh """
              docker tag ${ECR_REPO}:${IMAGE_TAG} \
              ${awsAccountID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}

              docker push ${awsAccountID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
            """
          }
        }
      }
    }

    stage('Deploy Docker Container') {
      environment {
        AUTH_SECRET = credentials('auth_secret')
        AUTH_GOOGLE_ID = credentials('auth_google_id')
        AUTH_GOOGLE_SECRET = credentials('auth_google_secret')
        MONGODB_URI = credentials('mongodb_uri')
        GITHUB_TOKEN = credentials('docs_flow_github_token')
      }

      steps {
        script {
          sshagent([DEPLOYMENT_KEY]) {
            withAWS(region: AWS_REGION, credentials: 'wm-ps-user-ecr') {

              def awsAccountID = sh(
                returnStdout: true,
                script: "aws sts get-caller-identity --query Account --output text"
              ).trim()

              sh """
                ssh -o StrictHostKeyChecking=no ubuntu@${REMOTE_SERVER} '
                  aws ecr get-login-password --region ${AWS_REGION} \
                  | docker login --username AWS --password-stdin \
                  ${awsAccountID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                '
              """

              // Remove old container if exists
              sh """
                ssh -o StrictHostKeyChecking=no ubuntu@${REMOTE_SERVER} '
                  docker rm -f ${CONTAINER_NAME} || true
                '
              """

              // Pull latest image
              sh """
                ssh -o StrictHostKeyChecking=no ubuntu@${REMOTE_SERVER} '
                  docker pull ${awsAccountID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
                '
              """

              sh """
                ssh -o StrictHostKeyChecking=no ubuntu@${REMOTE_SERVER} '
                  docker run -d \
                    --name ${CONTAINER_NAME} \
                    -p ${HTTP_PORT}:3000 \
                    -e AUTH_SECRET=${AUTH_SECRET} \
                    -e AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID} \
                    -e AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET} \
                    -e MONGODB_URI=${MONGODB_URI} \
                    -e GITHUB_TOKEN=${GITHUB_TOKEN} \
                    ${awsAccountID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
                '
              """
            }
          }
        }
      }
    }
  }
}
